---
Name: copyfactory_config
Before: 'mysite/*'
After: 'framework/*','cms/*'
---

SiteConfig:
  extensions:
    - CopyFactorySiteTreeExtension

LeftAndMain:
  extensions:
    - CopyFactorySiteTreeExtension_LeftAndMainExtension
